run:
  go: '1.21'

linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - containedctx
  - contextcheck
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - err113
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - fatcontext
  - forbidigo
  - forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecknoinits
  - gochecksumtype
  - goconst
  - gocritic
  - godot
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - ireturn
  - lll
  - loggercheck
  - makezero
  - mirror
  - misspell
  - musttag
  - nilerr
  - noctx
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tagliatelle
  - tenv
  - testableexamples
  - testifylint
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
  - zerologlint
  disable:
  - copyloopvar
  - cyclop
  - depguard
  - exhaustive
  - exhaustruct
  - funlen
  - gochecknoglobals
  - gocognit
  - gocyclo
  - godox
  - gomnd
  - intrange
  - maintidx
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - nonamedreturns
  - paralleltest
  - testpackage
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl

linters-settings:
  forbidigo:
    forbid:
    - ^fmt\.Print.*$
    - ^ioutil\..*$
    - ^os\.(DirEntry|FileInfo|FileMode|Is.*|Mode.*)$
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-shapefile)
  gofumpt:
    extra-rules: true
    module-path: github.com/twpayne/go-shapefile
  goimports:
    local-prefixes: github.com/twpayne/go-shapefile
  gosec:
    excludes:
    - G115
  ireturn:
    allow:
    - empty
    - error
    - github\.com/twpayne/go-geom\.T
    - stdlib
  misspell:
    locale: US
  stylecheck:
    checks:
    - all

issues:
  include:
  - EXC0011   # include issues about comments from `stylecheck`
  exclude-rules:
  - linters:
    - err113
    text: do not define dynamic errors, use wrapped static errors instead
  - linters:
    - gosec
    - lll
    path: _test\.go$
