linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - contextcheck
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exportloopref
  - forbidigo
  - forcetypeassert
  - gci
  - gocritic
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - interfacebloat
  - ireturn
  - lll
  - loggercheck
  - makezero
  - misspell
  - nilerr
  - noctx
  - nolintlint
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - revive
  - staticcheck
  - stylecheck
  - tagliatelle
  - testableexamples
  - tenv
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
  disable:
  - asasalint
  - cyclop
  - depguard
  - exhaustive
  - exhaustivestruct
  - exhaustruct
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goheader
  - gomnd
  - gomoddirectives
  - maintidx
  - maligned
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - nonamedreturns
  - nosnakecase
  - paralleltest
  - rowserrcheck # https://github.com/golangci/golangci-lint/issues/2649
  - sqlclosecheck # https://github.com/golangci/golangci-lint/issues/2649
  - structcheck # https://github.com/golangci/golangci-lint/issues/2649
  - testpackage
  - tparallel
  - varnamelen
  - wastedassign # https://github.com/golangci/golangci-lint/issues/2649
  - wrapcheck
  - wsl

linters-settings:
  forbidigo:
    forbid:
    - ^fmt\.Print.*$
    - ^ioutil\..*$
    - ^os\.(DirEntry|FileInfo|FileMode|Is.*|Mode.*)$
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-shapefile)
  gofumpt:
    extra-rules: true
    lang-version: '1.18'
    module-path: github.com/twpayne/go-shapefile
  goimports:
    local-prefixes: github.com/twpayne/go-shapefile
  ireturn:
    allow:
    - error
    - github\.com/twpayne/go-geom\.T
    - stdlib
  misspell:
    locale: US
  stylecheck:
    checks:
    - all

issues:
  include:
  - EXC0011   # include issues about comments from `stylecheck`
  exclude-rules:
  - linters:
    - goerr113
    text: do not define dynamic errors, use wrapped static errors instead
  - linters:
    - gosec
    - lll
    path: _test\.go$
